[package]
name = "autopilot"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]

[dependencies]
image = "0.19"
libc = "0.2.40"
rand = "0.4.2"
scopeguard = "0.3.3"

[dev-dependencies]
quickcheck = "*"

[build-dependencies]
pkg-config = "0.3.11"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { git = "https://github.com/servo/core-foundation-rs.git" }
core-graphics = { git = "https://github.com/servo/core-foundation-rs.git" }
cocoa = { git = "https://github.com/servo/core-foundation-rs.git" }

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.17.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["libloaderapi", "minwindef", "winbase", "winuser"] }
