[package]
name = "autopilot"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]

[dependencies]
image = "*"
libc = "*"
rand = "*"
scopeguard = "*"

[dev-dependencies]
quickcheck = "*"

[build-dependencies]
pkg-config = "*"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "*"
core-graphics = { git = "https://github.com/servo/core-foundation-rs.git" }
cocoa = { git = "https://github.com/servo/core-foundation-rs.git" }

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "minwindef", "winbase", "winuser"] }
